def configure():
    motor_1 = Motor(Port.E, Direction.COUNTERCLOCKWISE)
    motor_2 = Motor(Port.B, Direction.CLOCKWISE)
    motor = Motor(Port.F, Direction.CLOCKWISE)
    drive_base.settings(straight_speed=170)
    drive_base.settings(straight_acceleration=150)
    drive_base.settings(turn_rate=300)
    drive_base.settings(turn_acceleration=300)

def EAST2():
    configureEast2()
    """
    drive_base.turn(-12)
    drive_base.straight(-310)
    drive_base.turn(25)
    drive_base.straight(-70)
    drive_base.turn(30)
    drive_base.straight(-100)

    drive_base.straight(110)
    drive_base.turn(15)
    drive_base.straight(25)
    drive_base.turn(60)
    drive_base.straight(30)
    drive_base.turn(25)
    drive_base.straight(-50)
    drive_base.turn(80)
    # drive_base.straight(100)
    """
    drive_base.settings(turn_acceleration=200)
    drive_base.turn(-20, Stop.BRAKE)
    drive_base.straight(-225, Stop.BRAKE)
    drive_base.straight(100, Stop.BRAKE)
    drive_base.turn(25, Stop.BRAKE)
    drive_base.settings(straight_acceleration=250)
    drive_base.straight(-310, Stop.BRAKE)
    drive_base.turn(44.5, Stop.BRAKE)
    drive_base.straight(-60, Stop.BRAKE)
    drive_base.straight(140, Stop.BRAKE)
    drive_base.turn(100, Stop.BRAKE)
def EAST3():
    configure()
    drive_base.settings(straight_acceleration=100)
    drive_base.straight(150, Stop.BRAKE)
    drive_base.settings(straight_acceleration=500)
    drive_base.straight(-100, Stop.BRAKE)
    drive_base.straight(478, Stop.BRAKE)
    motor.run_angle(100, 85, Stop.BRAKE)
    drive_base.straight(-93, Stop.BRAKE)
    drive_base.straight(-15, Stop.BRAKE)
    motor.run_angle(100, -85, Stop.BRAKE)
    drive_base.turn(20, Stop.BRAKE)
    drive_base.curve(400,-70, Stop.BRAKE)

    drive_base.straight(-200, Stop.BRAKE)
    drive_base.turn(50, Stop.BRAKE)
    drive_base.straight(-200, Stop.BRAKE)
    drive_base.turn(-60, Stop.BRAKE)
    drive_base.straight(400, Stop.BRAKE)
    drive_base.turn(40, Stop.BRAKE)
    drive_base.straight(400, Stop.BRAKE)
