from BASEROBOT import *
def configureEast2():
    br.settings(straight_speed=170)
    br.settings(straight_acceleration=150)
    br.settings(turn_rate=300)
    br.settings(turn_acceleration=300)

def EAST2(br: BaseRobot):
    br.settings(straight_speed=170)
    br.settings(straight_acceleration=150)
    br.settings(turn_rate=300)
    br.settings(turn_acceleration=300)
    """
    br.turn(-12)
    br.straight(-310)
    br.turn(25)
    br.straight(-70)
    br.turn(30)
    br.straight(-100)

    br.straight(110)
    br.turn(15)
    br.straight(25)
    br.turn(60)
    br.straight(30)
    br.turn(25)
    br.straight(-50)
    br.turn(80)
    # br.straight(100)
    """
    br.settings(turn_acceleration=200)
    br.turn(-20, Stop.BRAKE)
    br.straight(-225, Stop.BRAKE)
    br.straight(100, Stop.BRAKE)
    br.turn(25, Stop.BRAKE)
    br.settings(straight_acceleration=250)
    br.straight(-310, Stop.BRAKE)
    br.turn(44.5, Stop.BRAKE)
    br.straight(-60, Stop.BRAKE)
    br.straight(140, Stop.BRAKE)
    br.turn(100, Stop.BRAKE)