if (not __name__ == "__main__"):
    from BASEROBOT import *
    def EAST3(br: BaseRobot):
        br.settings(straight_speed=170)
        br.settings(straight_acceleration=150)
        br.settings(turn_rate=300)
        br.settings(turn_acceleration=400)
        """
        br.turn(-12)
        br.straight(-310)
        br.turn(25)
        br.straight(-70)
        br.turn(30)
        br.straight(-100)

        br.straight(110)
        br.turn(15)
        br.straight(25)
        br.turn(60)
        br.straight(30)
        br.turn(25)
        br.straight(-50)
        br.turn(80)
        # br.straight(100)
        """
        br.settings(turn_acceleration=200)
        br.turn(-18.5, Stop.BRAKE)
        br.straight(225, Stop.BRAKE)
        br.straight(-100, Stop.BRAKE)
        br.turn(18.5, Stop.BRAKE)
        br.settings(straight_acceleration=250)
        br.straight(310, Stop.BRAKE)
        br.turn(30, Stop.BRAKE)
        br.straight(70, Stop.BRAKE)
        br.straight(-140, Stop.BRAKE)
        br.turn(92, Stop.BRAKE)
    def EAST2(br: BaseRobot):
        br.settings(straight_speed=300)
        br.settings(straight_acceleration=600)
        br.settings(turn_rate=700)
        br.settings(turn_acceleration=100)
        br.use_gyro(True)
        br.reset()

        # The main program starts here.
        br.straight(-600, Stop.BRAKE)
        #br.straight(-595, Stop.BRAKE)
        br.straight(150)
        br.turn(-2.5)
        br.straight(-160)
        br.front_attachment.run_angle(100,-85)
        br.straight(93, Stop.BRAKE)
        br.straight(19, Stop.BRAKE)
        br.front_attachment.run_angle(100, 85 )
        br.straight(95, Stop.BRAKE)
        br.turn(25, Stop.BRAKE)
        br.settings(straight_acceleration=825)
        br.straight(-100, Stop.BRAKE)
        br.turn(-10, Stop.BRAKE)
        br.straight(-285, Stop.BRAKE)
        br.settings(straight_acceleration=600)
        br.turn(-6, Stop.BRAKE)
        br.straight(300, Stop.NONE)
        br.turn(-50, Stop.NONE)
        br.straight(-85, Stop.NONE)
        br.turn(30, Stop.NONE)
        br.straight(-150, Stop.NONE)
        br.turn(50, Stop.NONE)
        br.straight(-700, Stop.BRAKE)
else:
    import FullCodeTemplate